package com.zenfit.common.enums;

public enum FitnessGoal {
    LOSE_WEIGHT,
    GAIN_MUSCLE,
    IMPROVE_ENDURANCE,
    MAINTAIN,
    REDUCE_STRESS,
    BETTER_SLEEP,
    TONE_BODY,
    INCREASE_STRENGTH,
    INCREASE_FLEXIBILITY,
    IMPROVE_POSTURE,
    INCREASE_ENERGY,
    BUILD_HABITS
}
